#!/usr/bin/env node

import { iot } from 'minaws/iot'

(async() => {
	const ws = await iot()
	ws.on('connect', () => {
		ws.subscribe('#', (err) => {
			if (err) console.log(err)
			ws.on('message', (topic,msg) => {
				console.log(topic,'==>',msg.toString())
				ws.end()
			})
			ws.publish('hello','hello world')
		})
		
	})
})()
